### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mmis1000** [mmis1000/irc-reply-bot#9]
- [x] fix file format for media and sound 
- [ ] finish all telegram related medias
  - [x] photo
  - [x] video
  - [x] sticker
  - [x] audio
  - [ ] document
- [x] replace current bind symbol implement with shell styled one
- [ ] notify telegram user when username not set
- [x] allow one user to have multi username for ban and other purpose
- [x] support user pic and custom display name

**Comment by Sea-n** [comment]
# 顯示 Telegram User Profile Photo, Chat Photo

可用 getUserProfilePhotos 取得頭貼

Group Photo 更新將會回傳 new_chat_photo
